import Mathlib.Data.Finset.Card
import Mathlib.Algebra.Polynomial.FieldDivision
import Mathlib.NumberTheory.FrobeniusNumber
import Mathlib.RingTheory.Polynomial.Cyclotomic.Roots
import Mathlib.Tactic

/-!
# Q-binomial quotient positivity at index gap four

Formal verification of the `l = k - 4` case of the q-binomial quotient
positivity conjecture. For `4 ≤ k ≤ n`, the quotient

`[n choose k]_q / [n choose (k - 4)]_q`

is represented by the four consecutive q-integer factors with
`a = n - k + 1` and `b = k - 3`.

This module machine-checks the exact reduction from polynomial divisibility
of the four-factor quotient to all of the finite semigroup conditions used in
in the proof. In particular, it proves the cyclotomic multiplicity criterion,
the sharp gap lemma, every large-`b` Hall case, and every small-`b` exception.

The standard weighted-complete-intersection construction is isolated as
`WeightedCompleteIntersectionBridge` and invoked once through the documented
literature axiom `weightedCompleteIntersectionBridge_external`. The final
coefficient-positivity theorems are unconditional Lean declarations whose only
project-specific axiom is that precisely cited external result.
-/

namespace QBinomialQuotientPositivityGapFour

open Polynomial

/-- The multiplicity with which `Φ_d` occurs in the product of the four
consecutive `q`-integers starting at `x`. -/
def multiplicity (x d : ℕ) : ℕ :=
  ((Finset.range 4).filter fun i ↦ d ∣ x + i).card

/-- The necessary and sufficient cyclotomic inequalities for the quotient
of the two four-term products to be a polynomial. -/
def CyclotomicCondition (a b : ℕ) : Prop :=
  ∀ d, 2 ≤ d → multiplicity b d ≤ multiplicity a d

/-- The fixed four-element index type used for numerator degrees and
denominator weights. -/
abbrev Index := Fin 4

def weight (b : ℕ) (j : Index) : ℕ := b + j

def degree (a : ℕ) (i : Index) : ℕ := a + i

/-- The additive semigroup generated by the weights indexed by `J`. -/
def weightSemigroup (b : ℕ) (J : Finset Index) : AddSubmonoid ℕ :=
  AddSubmonoid.closure (weight b '' (J : Set Index))

def Represented (a b : ℕ) (J : Finset Index) (i : Index) : Prop :=
  degree a i ∈ weightSemigroup b J

noncomputable def representedIndices (a b : ℕ) (J : Finset Index) : Finset Index :=
  letI := Classical.decPred (Represented a b J)
  Finset.univ.filter fun i ↦ Represented a b J i

/-- The Hall condition for the four denominator weights. -/
def HallCondition (a b : ℕ) : Prop :=
  ∀ J : Finset Index, J.Nonempty →
    J.card ≤ (representedIndices a b J).card

/-- The product `∏_{i=0}^3 (X^(x+i)-1)`. Four sign changes identify this
with the numerator or denominator product in equation (1). -/
noncomputable def fourProduct (R : Type*) [CommRing R] (x : ℕ) : Polynomial R :=
  ∏ i ∈ Finset.range 4, (Polynomial.X ^ (x + i) - 1)

noncomputable def IsPolynomialQuotient (a b : ℕ) : Prop :=
  fourProduct ℤ b ∣ fourProduct ℤ a

/-- Exact coefficient-positivity conclusion: the quotient is the image of
a polynomial with natural-number coefficients. -/
noncomputable def HasNonnegativeQuotient (a b : ℕ) : Prop :=
  ∃ Q : Polynomial ℕ,
    fourProduct ℤ a =
      fourProduct ℤ b * Q.map (Nat.castRingHom ℤ)

/-- The literal `q`-integer `[m]_q = 1 + q + ⋯ + q^(m-1)`.

This definition and the direct quotient interface below are adapted from the
Aristotle-generated companion formalization supplied with this project. -/
noncomputable def qInteger (m : ℕ) : Polynomial ℤ :=
  ∑ i ∈ Finset.range m, Polynomial.X ^ i

/-- The four consecutive `q`-integer factors beginning at `x`. -/
noncomputable def qIntegerProduct (x : ℕ) : Polynomial ℤ :=
  ∏ i ∈ Finset.range 4, qInteger (x + i)

/-- Polynomiality stated directly for the quotient occurring in the paper. -/
noncomputable def IsQIntegerPolynomialQuotient (a b : ℕ) : Prop :=
  qIntegerProduct b ∣ qIntegerProduct a

/-- Coefficientwise nonnegativity for the literal `q`-integer quotient. -/
noncomputable def HasNonnegativeQIntegerQuotient (a b : ℕ) : Prop :=
  ∃ Q : Polynomial ℕ,
    qIntegerProduct a =
      qIntegerProduct b * Q.map (Nat.castRingHom ℤ)

/-- Replace every integer coefficient by its natural-number representative.
When all coefficients are nonnegative, mapping this polynomial back to
`ℤ[X]` recovers the original polynomial. -/
noncomputable def coefficientwiseToNat (P : Polynomial ℤ) : Polynomial ℕ :=
  ⟨P.toFinsupp.mapRange Int.toNat (by simp)⟩

theorem coefficientwiseToNat_map_of_nonnegative
    (P : Polynomial ℤ) (hP : ∀ n, 0 ≤ P.coeff n) :
    (coefficientwiseToNat P).map (Nat.castRingHom ℤ) = P := by
  classical
  ext n
  rw [coeff_map]
  change ((P.coeff n).toNat : ℤ) = P.coeff n
  exact Int.natCast_toNat_eq_self.mpr (hP n)

lemma weight_mem_semigroup {b : ℕ} {J : Finset Index} {j : Index}
    (hj : j ∈ J) :
    weight b j ∈ weightSemigroup b J := by
  apply AddSubmonoid.subset_closure
  exact ⟨j, hj, rfl⟩

lemma multiple_weight_mem_semigroup
    {b n : ℕ} {J : Finset Index} {j : Index}
    (hj : j ∈ J) (hdiv : weight b j ∣ n) :
    n ∈ weightSemigroup b J := by
  obtain ⟨c, rfl⟩ := hdiv
  simpa [nsmul_eq_mul, Nat.mul_comm] using
    (weightSemigroup b J).nsmul_mem (weight_mem_semigroup hj) c

lemma X_pow_sub_one_ne_zero
    {R : Type*} [CommRing R] [Nontrivial R] {m : ℕ} (hm : 0 < m) :
    (Polynomial.X ^ m - 1 : Polynomial R) ≠ 0 := by
  intro h
  have hdeg :
      (Polynomial.X ^ m - 1 : Polynomial R).natDegree = m := by
    simpa using Polynomial.natDegree_X_pow_sub_C
      (R := R) (n := m) (r := (1 : R))
  rw [h, Polynomial.natDegree_zero] at hdeg
  omega

/-- The standard geometric-series identity for the literal `q`-integer. -/
lemma qInteger_mul_X_sub_one (m : ℕ) :
    qInteger m * (Polynomial.X - 1) = Polynomial.X ^ m - 1 := by
  simpa [qInteger] using (geom_sum_mul Polynomial.X m)

/-- Coefficients of a `q`-integer. Ported from the Aristotle formalization. -/
theorem qInteger_coeff (m k : ℕ) :
    (qInteger m).coeff k = if k < m then 1 else 0 := by
  simp only [qInteger, finsetSum_coeff, coeff_X_pow]
  by_cases h : k < m
  · rw [Finset.sum_eq_single k]
    · simp [h]
    · intro i _ hik
      simp [Ne.symm hik]
    · intro hk
      exact absurd (Finset.mem_range.mpr h) hk
  · simp only [if_neg h]
    apply Finset.sum_eq_zero
    intro i hi
    rw [Finset.mem_range] at hi
    rw [if_neg]
    omega

/-- Degree of a positive `q`-integer. Ported from the Aristotle
formalization. -/
theorem qInteger_natDegree (m : ℕ) (hm : 1 ≤ m) :
    (qInteger m).natDegree = m - 1 := by
  induction m with
  | zero => omega
  | succ n ih =>
    rcases Nat.eq_zero_or_pos n with hn | hn
    · subst hn
      simp [qInteger]
    · have hstep : qInteger (n + 1) = qInteger n + X ^ n := by
        simp [qInteger, Finset.sum_range_succ]
      rw [hstep]
      have hdeg :
          (qInteger n).natDegree < (X ^ n : Polynomial ℤ).natDegree := by
        rw [ih hn, natDegree_X_pow]
        omega
      rw [natDegree_add_eq_right_of_natDegree_lt hdeg, natDegree_X_pow]
      omega

theorem qInteger_ne_zero (m : ℕ) (hm : 1 ≤ m) :
    qInteger m ≠ 0 := by
  intro h
  have hc : (qInteger m).coeff (m - 1) = 1 := by
    rw [qInteger_coeff]
    simp
    omega
  rw [h] at hc
  simp at hc

/-- The degree of the paper's four-factor numerator or denominator block. -/
theorem qIntegerProduct_natDegree (x : ℕ) (hx : 1 ≤ x) :
    (qIntegerProduct x).natDegree = 4 * x + 2 := by
  rw [qIntegerProduct,
    natDegree_prod _ _ (fun i _ => qInteger_ne_zero _ (by omega))]
  rw [Finset.sum_range_succ, Finset.sum_range_succ,
    Finset.sum_range_succ, Finset.sum_range_one]
  rw [qInteger_natDegree _ (by omega), qInteger_natDegree _ (by omega),
    qInteger_natDegree _ (by omega), qInteger_natDegree _ (by omega)]
  omega

theorem qIntegerProduct_ne_zero (x : ℕ) (hx : 1 ≤ x) :
    qIntegerProduct x ≠ 0 := by
  rw [qIntegerProduct, Finset.prod_ne_zero_iff]
  intro i hi
  apply qInteger_ne_zero
  have hi := Finset.mem_range.mp hi
  omega

/-- Cancelling the four common `(X - 1)` factors identifies the literal
`q`-integer product with the product used for the cyclotomic argument. -/
lemma fourProduct_eq_qIntegerProduct_mul (x : ℕ) :
    fourProduct ℤ x =
      qIntegerProduct x * (Polynomial.X - 1) ^ 4 := by
  rw [fourProduct, qIntegerProduct]
  calc
    ∏ i ∈ Finset.range 4, (Polynomial.X ^ (x + i) - 1 : Polynomial ℤ) =
        ∏ i ∈ Finset.range 4,
          (qInteger (x + i) * (Polynomial.X - 1)) := by
            apply Finset.prod_congr rfl
            intro i hi
            exact (qInteger_mul_X_sub_one (x + i)).symm
    _ = (∏ i ∈ Finset.range 4, qInteger (x + i)) *
          ∏ _i ∈ Finset.range 4, (Polynomial.X - 1 : Polynomial ℤ) := by
            simp only [Finset.prod_mul_distrib]
    _ = qIntegerProduct x * (Polynomial.X - 1) ^ 4 := by
          simp [qIntegerProduct]

lemma X_sub_one_pow_four_ne_zero :
    ((Polynomial.X - 1) ^ 4 : Polynomial ℤ) ≠ 0 := by
  apply pow_ne_zero
  simpa using
    (X_pow_sub_one_ne_zero (R := ℤ) (m := 1) (by omega))

/-- Polynomiality for the paper's literal `q`-integer quotient is exactly
polynomiality for the four `(X^m - 1)` factors. -/
theorem isQIntegerPolynomialQuotient_iff (a b : ℕ) :
    IsQIntegerPolynomialQuotient a b ↔ IsPolynomialQuotient a b := by
  rw [IsQIntegerPolynomialQuotient, IsPolynomialQuotient]
  constructor
  · rintro ⟨P, hP⟩
    refine ⟨P, ?_⟩
    rw [fourProduct_eq_qIntegerProduct_mul,
      fourProduct_eq_qIntegerProduct_mul, hP]
    ac_rfl
  · rintro ⟨P, hP⟩
    refine ⟨P, ?_⟩
    rw [fourProduct_eq_qIntegerProduct_mul,
      fourProduct_eq_qIntegerProduct_mul] at hP
    apply mul_right_cancel₀ X_sub_one_pow_four_ne_zero
    simpa only [mul_assoc, mul_left_comm, mul_comm] using hP

/-- The two exact natural-coefficient formulations of positivity agree. -/
theorem hasNonnegativeQIntegerQuotient_iff (a b : ℕ) :
    HasNonnegativeQIntegerQuotient a b ↔ HasNonnegativeQuotient a b := by
  rw [HasNonnegativeQIntegerQuotient, HasNonnegativeQuotient]
  constructor
  · rintro ⟨Q, hQ⟩
    refine ⟨Q, ?_⟩
    rw [fourProduct_eq_qIntegerProduct_mul,
      fourProduct_eq_qIntegerProduct_mul, hQ]
    ac_rfl
  · rintro ⟨Q, hQ⟩
    refine ⟨Q, ?_⟩
    rw [fourProduct_eq_qIntegerProduct_mul,
      fourProduct_eq_qIntegerProduct_mul] at hQ
    apply mul_right_cancel₀ X_sub_one_pow_four_ne_zero
    simpa only [mul_assoc, mul_left_comm, mul_comm] using hQ

lemma rootMultiplicity_X_pow_sub_one_of_primitive
    {ζ : ℂ} {d m : ℕ} (hd : 2 ≤ d) (hm : 0 < m)
    (hζ : IsPrimitiveRoot ζ d) :
    Polynomial.rootMultiplicity ζ
      (Polynomial.X ^ m - 1 : Polynomial ℂ) =
        if d ∣ m then 1 else 0 := by
  have hp : (Polynomial.X ^ m - 1 : Polynomial ℂ) ≠ 0 :=
    X_pow_sub_one_ne_zero hm
  by_cases hdm : d ∣ m
  · have hroot : (Polynomial.X ^ m - 1 : Polynomial ℂ).IsRoot ζ := by
      rw [Polynomial.IsRoot, Polynomial.eval_sub, Polynomial.eval_X_pow,
        Polynomial.eval_one, (hζ.pow_eq_one_iff_dvd m).mpr hdm, sub_self]
    have hderiv :
        ¬(Polynomial.X ^ m - 1 : Polynomial ℂ).derivative.IsRoot ζ := by
      rw [Polynomial.IsRoot, Polynomial.derivative_sub,
        Polynomial.derivative_X_pow]
      simp only [Polynomial.derivative_one, sub_zero, Polynomial.eval_C_mul,
        Polynomial.eval_X_pow]
      exact mul_ne_zero (Nat.cast_ne_zero.mpr hm.ne')
        (pow_ne_zero _ (hζ.ne_zero (by omega)))
    have hnot :
        ¬1 < Polynomial.rootMultiplicity ζ
          (Polynomial.X ^ m - 1 : Polynomial ℂ) := by
      rw [Polynomial.one_lt_rootMultiplicity_iff_isRoot hp]
      exact fun h ↦ hderiv h.2
    have hpos :
        0 < Polynomial.rootMultiplicity ζ
          (Polynomial.X ^ m - 1 : Polynomial ℂ) :=
      (Polynomial.rootMultiplicity_pos hp).2 hroot
    simp [hdm]
    omega
  · have hnroot : ¬(Polynomial.X ^ m - 1 : Polynomial ℂ).IsRoot ζ := by
      rw [Polynomial.IsRoot, Polynomial.eval_sub, Polynomial.eval_X_pow,
        Polynomial.eval_one, sub_eq_zero]
      exact fun h ↦ hdm ((hζ.pow_eq_one_iff_dvd m).mp h)
    rw [Polynomial.rootMultiplicity_eq_zero hnroot, if_neg hdm]

lemma fourProduct_ne_zero
    {R : Type*} [CommRing R] [IsDomain R] {x : ℕ} (hx : 1 ≤ x) :
    fourProduct R x ≠ 0 := by
  rw [fourProduct, Finset.prod_ne_zero_iff]
  intro i hi
  apply X_pow_sub_one_ne_zero
  have hi := Finset.mem_range.mp hi
  omega

lemma rootMultiplicity_finset_prod
    {ζ : ℂ} {ι : Type*} [DecidableEq ι]
    (s : Finset ι) (f : ι → Polynomial ℂ)
    (hf : ∀ i ∈ s, f i ≠ 0) :
    Polynomial.rootMultiplicity ζ (∏ i ∈ s, f i) =
      ∑ i ∈ s, Polynomial.rootMultiplicity ζ (f i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert i s hi ih =>
      have hfi : f i ≠ 0 := hf i (by simp)
      have hfs : ∏ j ∈ s, f j ≠ 0 := by
        rw [Finset.prod_ne_zero_iff]
        intro j hj
        exact hf j (by simp [hj])
      rw [Finset.prod_insert hi, Finset.sum_insert hi,
        Polynomial.rootMultiplicity_mul (mul_ne_zero hfi hfs)]
      congr
      exact ih (fun j hj ↦ hf j (by simp [hj]))

lemma rootMultiplicity_fourProduct
    {ζ : ℂ} {x d : ℕ} (hx : 1 ≤ x) (hd : 2 ≤ d)
    (hζ : IsPrimitiveRoot ζ d) :
    Polynomial.rootMultiplicity ζ (fourProduct ℂ x) =
      multiplicity x d := by
  rw [fourProduct,
    rootMultiplicity_finset_prod (Finset.range 4)
      (fun i ↦ (Polynomial.X ^ (x + i) - 1 : Polynomial ℂ))]
  · rw [multiplicity, Finset.card_filter]
    apply Finset.sum_congr rfl
    intro i hi
    rw [rootMultiplicity_X_pow_sub_one_of_primitive hd
      (Nat.add_pos_left (by omega) i) hζ]
  · intro i hi
    exact X_pow_sub_one_ne_zero (by omega)

lemma fourProduct_map
    {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (x : ℕ) :
    (fourProduct R x).map f = fourProduct S x := by
  simp [fourProduct, Polynomial.map_prod]

/-- Section 1's cyclotomic consequence, proved through multiplicities at a
primitive complex root. -/
theorem cyclotomicCondition_of_polynomialQuotient
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (hpoly : IsPolynomialQuotient a b) :
    CyclotomicCondition a b := by
  intro d hd
  let ζ := Complex.exp (2 * (Real.pi : ℂ) * Complex.I / d)
  have hζ : IsPrimitiveRoot ζ d := by
    dsimp [ζ]
    exact Complex.isPrimitiveRoot_exp d (by omega)
  have hdivC : fourProduct ℂ b ∣ fourProduct ℂ a := by
    have hmap := Polynomial.map_dvd (Int.castRingHom ℂ) hpoly
    simpa [fourProduct_map] using hmap
  have hmul :=
    Polynomial.rootMultiplicity_le_rootMultiplicity_of_dvd
      (fourProduct_ne_zero (R := ℂ) ha) hdivC ζ
  simpa [rootMultiplicity_fourProduct hb hd hζ,
    rootMultiplicity_fourProduct ha hd hζ] using hmul

lemma exists_numerator_multiple
    {a b d j : ℕ} (hcyclo : CyclotomicCondition a b)
    (hd : 2 ≤ d) (hj : j < 4) (hdiv : d ∣ b + j) :
    ∃ i < 4, d ∣ a + i := by
  have hbpos : 0 < multiplicity b d := by
    rw [multiplicity, Finset.card_pos]
    exact ⟨j, Finset.mem_filter.mpr ⟨Finset.mem_range.mpr hj, hdiv⟩⟩
  have hapos : 0 < multiplicity a d :=
    lt_of_lt_of_le hbpos (hcyclo d hd)
  rw [multiplicity, Finset.card_pos] at hapos
  obtain ⟨i, hi⟩ := hapos
  simp only [Finset.mem_filter, Finset.mem_range] at hi
  exact ⟨i, hi.1, hi.2⟩

/-- The four denominator weights each divide a member of the numerator
block.  This is the only consequence of the cyclotomic inequalities used by
the gap lemma. -/
lemma denominator_weights_are_covered
    {a b : ℕ} (hb : 5 ≤ b) (hcyclo : CyclotomicCondition a b) :
    ∀ j < 4, ∃ x : ℕ, a ≤ x * (b + j) ∧ x * (b + j) ≤ a + 3 := by
  intro j hj
  obtain ⟨i, hi, hdiv⟩ :=
    exists_numerator_multiple hcyclo (by omega : 2 ≤ b + j) hj
      (dvd_refl (b + j))
  obtain ⟨x, hx⟩ := hdiv
  refine ⟨x, ?_, ?_⟩
  · rw [Nat.mul_comm, ← hx]
    omega
  · rw [Nat.mul_comm, ← hx]
    omega

/-- Section 3's singleton condition, including the exceptional weight `1`
which is not covered by the `d ≥ 2` cyclotomic convention. -/
theorem singleton_weight_is_covered
    {a b j : ℕ} (hb : 1 ≤ b) (hj : j < 4)
    (hcyclo : CyclotomicCondition a b) :
    ∃ i < 4, b + j ∣ a + i := by
  by_cases h : b + j = 1
  · exact ⟨0, by omega, by simp [h]⟩
  · exact exists_numerator_multiple hcyclo (by omega) hj (dvd_refl (b + j))

/-- The degree comparison from Section 1, derived directly from coverage of
the largest denominator weight. -/
theorem cyclotomic_implies_a_ge_b
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (hcyclo : CyclotomicCondition a b) :
    b ≤ a := by
  obtain ⟨i, hi, hdiv⟩ :=
    exists_numerator_multiple hcyclo (d := b + 3) (j := 3)
      (by omega) (by omega) (by simp)
  obtain ⟨c, hc⟩ := hdiv
  by_contra h
  have hcpos : 1 ≤ c := by
    by_contra hc0
    have : c = 0 := by omega
    simp [this] at hc
    omega
  nlinarith

/-- The eight-case arithmetic heart of the gap lemma. -/
private lemma gap_core
    {a b x₀ x₁ x₂ x₃ : ℕ}
    (ha : 1 ≤ a) (hb : 5 ≤ b) (haT : a ≤ b * (b + 3) - 2)
    (h₀l : a ≤ x₀ * b)       (h₀u : x₀ * b ≤ a + 3)
    (h₁l : a ≤ x₁ * (b + 1)) (h₁u : x₁ * (b + 1) ≤ a + 3)
    (h₂l : a ≤ x₂ * (b + 2)) (h₂u : x₂ * (b + 2) ≤ a + 3)
    (h₃l : a ≤ x₃ * (b + 3)) (h₃u : x₃ * (b + 3) ≤ a + 3) :
    a = b := by
  have hx₀ : 1 ≤ x₀ := by
    by_contra h
    have : x₀ = 0 := by omega
    simp [this] at h₀l
    omega
  have hx₁ : 1 ≤ x₁ := by
    by_contra h
    have : x₁ = 0 := by omega
    simp [this] at h₁l
    omega
  have hx₂ : 1 ≤ x₂ := by
    by_contra h
    have : x₂ = 0 := by omega
    simp [this] at h₂l
    omega
  have hx₃ : 1 ≤ x₃ := by
    by_contra h
    have : x₃ = 0 := by omega
    simp [this] at h₃l
    omega

  have hTpos : 2 ≤ b * (b + 3) := by nlinarith
  have haT' : a + 2 ≤ b * (b + 3) := by omega

  have hx₁_le : x₁ ≤ b + 1 := by
    by_contra h
    have hmul : (b + 2) * (b + 1) ≤ x₁ * (b + 1) :=
      Nat.mul_le_mul_right (b + 1) (by omega)
    nlinarith only [hmul, h₁u, haT']
  have hx₂_le : x₂ ≤ b := by
    by_contra h
    have hmul : (b + 1) * (b + 2) ≤ x₂ * (b + 2) :=
      Nat.mul_le_mul_right (b + 2) (by omega)
    nlinarith only [hmul, h₂u, haT']
  have hx₃_le : x₃ ≤ b := by
    by_contra h
    have hmul : (b + 1) * (b + 3) ≤ x₃ * (b + 3) :=
      Nat.mul_le_mul_right (b + 3) (by omega)
    nlinarith only [hmul, h₃u, haT']

  have h₀₁ : x₁ ≤ x₀ := by
    by_contra h
    have hmul : (x₀ + 1) * (b + 1) ≤ x₁ * (b + 1) :=
      Nat.mul_le_mul_right (b + 1) (by omega)
    nlinarith only [hmul, h₀l, h₁u, hb, hx₀]
  have h₁₂ : x₂ ≤ x₁ := by
    by_contra h
    have hmul : (x₁ + 1) * (b + 2) ≤ x₂ * (b + 2) :=
      Nat.mul_le_mul_right (b + 2) (by omega)
    nlinarith only [hmul, h₁l, h₂u, hb, hx₁]
  have h₂₃ : x₃ ≤ x₂ := by
    by_contra h
    have hmul : (x₂ + 1) * (b + 3) ≤ x₃ * (b + 3) :=
      Nat.mul_le_mul_right (b + 3) (by omega)
    nlinarith only [hmul, h₂l, h₃u, hb, hx₂]

  have h₀₁' : x₀ ≤ x₁ + 1 := by
    by_contra h
    have hmul : (x₁ + 2) * b ≤ x₀ * b :=
      Nat.mul_le_mul_right b (by omega)
    nlinarith only [hmul, h₁l, h₀u, hx₁_le, hb]
  have h₁₂' : x₁ ≤ x₂ + 1 := by
    by_contra h
    have hmul : (x₂ + 2) * (b + 1) ≤ x₁ * (b + 1) :=
      Nat.mul_le_mul_right (b + 1) (by omega)
    nlinarith only [hmul, h₂l, h₁u, hx₂_le, hb]
  have h₂₃' : x₂ ≤ x₃ + 1 := by
    by_contra h
    have hmul : (x₃ + 2) * (b + 2) ≤ x₂ * (b + 2) :=
      Nat.mul_le_mul_right (b + 2) (by omega)
    nlinarith only [hmul, h₃l, h₂u, hx₃_le, hb]

  rcases (by omega : x₀ = x₁ ∨ x₀ = x₁ + 1) with h₀ | h₀ <;>
    rcases (by omega : x₁ = x₂ ∨ x₁ = x₂ + 1) with h₁ | h₁ <;>
      rcases (by omega : x₂ = x₃ ∨ x₂ = x₃ + 1) with h₂ | h₂
  · -- 000
    subst x₀
    subst x₁
    subst x₂
    nlinarith only [h₀l, h₃u, hx₃]
  · -- 001
    subst x₀
    subst x₁
    subst x₂
    nlinarith only [h₀l, h₂u, hx₃]
  · -- 010
    subst x₀
    subst x₁
    subst x₂
    nlinarith only [h₀l, h₁u, h₂l, hb, hx₃]
  · -- 011
    subst x₀
    subst x₁
    subst x₂
    nlinarith only [h₀l, h₁u, h₂l, hb, hx₃]
  · -- 100
    subst x₀
    subst x₁
    subst x₂
    nlinarith only [h₁l, h₃u, h₀u, hb, hx₃]
  · -- 101
    subst x₀
    subst x₁
    subst x₂
    nlinarith only [h₁l, h₂u, h₃l, hb, hx₃]
  · -- 110
    subst x₀
    subst x₁
    subst x₂
    nlinarith only [h₂l, h₃u, h₀u, hb, hx₃]
  · -- 111
    subst x₀
    subst x₁
    subst x₂
    have hxb : b ≤ x₃ := by
      by_contra h
      have hstep : x₃ + 1 ≤ b := by omega
      nlinarith only [h₃l, h₁u, hstep]
    have : x₃ = b := by omega
    subst x₃
    nlinarith only [h₁u, haT']

/-- The sharp index-gap-four gap lemma for `b ≥ 5`. -/
theorem gap_lemma
    {a b : ℕ} (ha : 1 ≤ a) (hb : 5 ≤ b)
    (hcyclo : CyclotomicCondition a b) :
    a = b ∨ b * (b + 3) - 1 ≤ a := by
  by_cases hlarge : b * (b + 3) - 1 ≤ a
  · exact Or.inr hlarge
  · left
    have haT : a ≤ b * (b + 3) - 2 := by omega
    have hcov := denominator_weights_are_covered hb hcyclo
    obtain ⟨x₀, h₀l, h₀u⟩ := hcov 0 (by omega)
    obtain ⟨x₁, h₁l, h₁u⟩ := hcov 1 (by omega)
    obtain ⟨x₂, h₂l, h₂u⟩ := hcov 2 (by omega)
    obtain ⟨x₃, h₃l, h₃u⟩ := hcov 3 (by omega)
    norm_num at h₀l h₀u h₁l h₁u h₂l h₂u h₃l h₃u
    exact gap_core ha hb haT h₀l h₀u h₁l h₁u h₂l h₂u h₃l h₃u

/-- Membership in the additive semigroup generated by two natural numbers. -/
def TwoGenerated (x y n : ℕ) : Prop :=
  ∃ r s : ℕ, n = r * x + s * y

def ThreeGenerated (x y z n : ℕ) : Prop :=
  ∃ r s t : ℕ, n = r * x + s * y + t * z

lemma TwoGenerated.toThreeGenerated {x y z n : ℕ}
    (h : TwoGenerated x y n) :
    ThreeGenerated x y z n := by
  obtain ⟨r, s, hrs⟩ := h
  exact ⟨r, s, 0, by simpa using hrs⟩

lemma TwoGenerated.toThreeGeneratedOuter {x y z n : ℕ}
    (h : TwoGenerated x z n) :
    ThreeGenerated x y z n := by
  obtain ⟨r, t, hrt⟩ := h
  exact ⟨r, 0, t, by simpa using hrt⟩

lemma TwoGenerated.toThreeGeneratedLast {x y z n : ℕ}
    (h : TwoGenerated y z n) :
    ThreeGenerated x y z n := by
  obtain ⟨s, t, hst⟩ := h
  exact ⟨0, s, t, by simpa using hst⟩

/-- The two-generator Frobenius assertion used in Section 3, in its coprime
form. -/
theorem coprime_frobenius_bound
    {x y n : ℕ} (hcop : x.Coprime y) (hx : 1 < x) (hy : 1 < y)
    (hn : x * y - x - y < n) :
    TwoGenerated x y n := by
  have hF := (frobeniusNumber_iff.mp (frobeniusNumber_pair hcop hx hy)).2 n hn
  rw [AddSubmonoid.mem_closure_pair] at hF
  obtain ⟨r, s, hrs⟩ := hF
  exact ⟨r, s, by simpa [nsmul_eq_mul, Nat.mul_comm] using hrs.symm⟩

/-- The exact small-generator gap tables used in Section 6. Each theorem
states the nongap direction needed by the proof; the excluded values are
also easily seen to be impossible by `omega`. -/
theorem generated_234 {n : ℕ} (hn : 2 ≤ n) :
    ThreeGenerated 2 3 4 n := by
  exact (coprime_frobenius_bound (by decide) (by omega) (by omega)
    (by omega)).toThreeGenerated

theorem generated_235 {n : ℕ} (hn : 2 ≤ n) :
    ThreeGenerated 2 3 5 n := by
  exact (coprime_frobenius_bound (by decide) (by omega) (by omega)
    (by omega)).toThreeGenerated

theorem generated_245 {n : ℕ} (hn : 2 ≤ n) (h3 : n ≠ 3) :
    ThreeGenerated 2 4 5 n := by
  by_cases h2 : n = 2
  · subst n
    exact ⟨1, 0, 0, by norm_num⟩
  exact (coprime_frobenius_bound (x := 2) (y := 5)
    (by decide) (by omega) (by omega) (by omega)).toThreeGeneratedOuter

theorem generated_345 {n : ℕ} (hn : 3 ≤ n) :
    ThreeGenerated 3 4 5 n := by
  by_cases hlarge : 5 < n
  · exact (coprime_frobenius_bound (by decide) (by omega) (by omega)
      hlarge).toThreeGenerated
  rcases (by omega : n = 3 ∨ n = 4 ∨ n = 5) with rfl | rfl | rfl
  · exact ⟨1, 0, 0, by norm_num⟩
  · exact ⟨0, 1, 0, by norm_num⟩
  · exact ⟨0, 0, 1, by norm_num⟩

theorem generated_346 {n : ℕ} (hn : 3 ≤ n) (h5 : n ≠ 5) :
    ThreeGenerated 3 4 6 n := by
  by_cases hlarge : 5 < n
  · exact (coprime_frobenius_bound (by decide) (by omega) (by omega)
      hlarge).toThreeGenerated
  rcases (by omega : n = 3 ∨ n = 4) with rfl | rfl
  · exact ⟨1, 0, 0, by norm_num⟩
  · exact ⟨0, 1, 0, by norm_num⟩

theorem generated_356 {n : ℕ} (hn : 3 ≤ n)
    (h4 : n ≠ 4) (h7 : n ≠ 7) :
    ThreeGenerated 3 5 6 n := by
  by_cases hlarge : 7 < n
  · exact (coprime_frobenius_bound (by decide) (by omega) (by omega)
      hlarge).toThreeGenerated
  rcases (by omega : n = 3 ∨ n = 5 ∨ n = 6) with rfl | rfl | rfl
  · exact ⟨1, 0, 0, by norm_num⟩
  · exact ⟨0, 1, 0, by norm_num⟩
  · exact ⟨0, 0, 1, by norm_num⟩

theorem generated_456 {n : ℕ} (hn : 3 ≤ n)
    (h3 : n ≠ 3) (h7 : n ≠ 7) :
    ThreeGenerated 4 5 6 n := by
  by_cases hlarge : 11 < n
  · exact (coprime_frobenius_bound (by decide) (by omega) (by omega)
      hlarge).toThreeGenerated
  rcases (by omega :
      n = 4 ∨ n = 5 ∨ n = 6 ∨ n = 8 ∨ n = 9 ∨ n = 10 ∨ n = 11) with
    rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact ⟨1, 0, 0, by norm_num⟩
  · exact ⟨0, 1, 0, by norm_num⟩
  · exact ⟨0, 0, 1, by norm_num⟩
  · exact ⟨2, 0, 0, by norm_num⟩
  · exact ⟨1, 1, 0, by norm_num⟩
  · exact ⟨0, 2, 0, by norm_num⟩
  · exact ⟨0, 1, 1, by norm_num⟩

theorem generated_457 {n : ℕ} (hn : 4 ≤ n) (h6 : n ≠ 6) :
    ThreeGenerated 4 5 7 n := by
  by_cases hlarge : 11 < n
  · exact (coprime_frobenius_bound (by decide) (by omega) (by omega)
      hlarge).toThreeGenerated
  rcases (by omega :
      n = 4 ∨ n = 5 ∨ n = 7 ∨ n = 8 ∨ n = 9 ∨ n = 10 ∨ n = 11) with
    rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact ⟨1, 0, 0, by norm_num⟩
  · exact ⟨0, 1, 0, by norm_num⟩
  · exact ⟨0, 0, 1, by norm_num⟩
  · exact ⟨2, 0, 0, by norm_num⟩
  · exact ⟨1, 1, 0, by norm_num⟩
  · exact ⟨0, 2, 0, by norm_num⟩
  · exact ⟨1, 0, 1, by norm_num⟩

theorem generated_467 {n : ℕ} (hn : 4 ≤ n)
    (h5 : n ≠ 5) (h9 : n ≠ 9) :
    ThreeGenerated 4 6 7 n := by
  by_cases hlarge : 17 < n
  · exact (coprime_frobenius_bound (x := 4) (y := 7)
      (by decide) (by omega) (by omega) hlarge).toThreeGeneratedOuter
  rcases (by omega :
      n = 4 ∨ n = 6 ∨ n = 7 ∨ n = 8 ∨ n = 10 ∨ n = 11 ∨
      n = 12 ∨ n = 13 ∨ n = 14 ∨ n = 15 ∨ n = 16 ∨ n = 17) with
    rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact ⟨1, 0, 0, by norm_num⟩
  · exact ⟨0, 1, 0, by norm_num⟩
  · exact ⟨0, 0, 1, by norm_num⟩
  · exact ⟨2, 0, 0, by norm_num⟩
  · exact ⟨1, 1, 0, by norm_num⟩
  · exact ⟨1, 0, 1, by norm_num⟩
  · exact ⟨3, 0, 0, by norm_num⟩
  · exact ⟨0, 1, 1, by norm_num⟩
  · exact ⟨0, 0, 2, by norm_num⟩
  · exact ⟨2, 0, 1, by norm_num⟩
  · exact ⟨4, 0, 0, by norm_num⟩
  · exact ⟨1, 1, 1, by norm_num⟩

theorem generated_567 {n : ℕ} (hn : 4 ≤ n)
    (h4 : n ≠ 4) (h8 : n ≠ 8) (h9 : n ≠ 9) :
    ThreeGenerated 5 6 7 n := by
  by_cases hlarge : 19 < n
  · exact (coprime_frobenius_bound (by decide) (by omega) (by omega)
      hlarge).toThreeGenerated
  rcases (by omega :
      n = 5 ∨ n = 6 ∨ n = 7 ∨ n = 10 ∨ n = 11 ∨ n = 12 ∨
      n = 13 ∨ n = 14 ∨ n = 15 ∨ n = 16 ∨ n = 17 ∨ n = 18 ∨ n = 19) with
    rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact ⟨1, 0, 0, by norm_num⟩
  · exact ⟨0, 1, 0, by norm_num⟩
  · exact ⟨0, 0, 1, by norm_num⟩
  · exact ⟨2, 0, 0, by norm_num⟩
  · exact ⟨1, 1, 0, by norm_num⟩
  · exact ⟨0, 2, 0, by norm_num⟩
  · exact ⟨0, 1, 1, by norm_num⟩
  · exact ⟨0, 0, 2, by norm_num⟩
  · exact ⟨3, 0, 0, by norm_num⟩
  · exact ⟨2, 1, 0, by norm_num⟩
  · exact ⟨2, 0, 1, by norm_num⟩
  · exact ⟨0, 3, 0, by norm_num⟩
  · exact ⟨1, 0, 2, by norm_num⟩

/-- The scaled two-generator Frobenius estimate in exactly the form needed
for a four-term interval. If `M` is a multiple of `gcd x y`, lies no more
than three below `lcm x y`, and `x + y > 3`, then `M` is generated by
`x` and `y`. -/
theorem pair_frobenius_from_lcm
    {x y M : ℕ} (hx : 0 < x) (hy : 0 < y)
    (hdiv : x.gcd y ∣ M) (hnear : x.lcm y ≤ M + 3)
    (hxy : 3 < x + y) :
    TwoGenerated x y M := by
  let g := x.gcd y
  let u := x / g
  let v := y / g
  let m := M / g
  have hg : 0 < g := by
    dsimp [g]
    exact Nat.gcd_pos_of_pos_left y hx
  have hgx : g * u = x := by
    dsimp [g, u]
    exact Nat.mul_div_cancel' (Nat.gcd_dvd_left x y)
  have hgy : g * v = y := by
    dsimp [g, v]
    exact Nat.mul_div_cancel' (Nat.gcd_dvd_right x y)
  have hgM : g * m = M := by
    dsimp [g, m]
    exact Nat.mul_div_cancel' hdiv
  by_cases hu : u = 1
  · refine ⟨m, 0, ?_⟩
    rw [← hgM, ← hgx, hu]
    ring
  by_cases hv : v = 1
  · refine ⟨0, m, ?_⟩
    rw [← hgM, ← hgy, hv]
    ring
  have hu2 : 2 ≤ u := by
    have hu0 : u ≠ 0 := by
      intro hu0
      rw [hu0, mul_zero] at hgx
      omega
    exact (Nat.two_le_iff u).2 ⟨hu0, hu⟩
  have hv2 : 2 ≤ v := by
    have hv0 : v ≠ 0 := by
      intro hv0
      rw [hv0, mul_zero] at hgy
      omega
    exact (Nat.two_le_iff v).2 ⟨hv0, hv⟩
  have huv : u + v ≤ u * v := by nlinarith
  have hFadd : u * v - u - v + (u + v) = u * v := by omega
  have hlcm : x.lcm y = g * (u * v) := by
    apply Nat.mul_left_cancel hg
    calc
      g * x.lcm y = x * y := Nat.gcd_mul_lcm x y
      _ = g * (g * (u * v)) := by rw [← hgx, ← hgy]; ring
  have hscaled :
      g * (u * v - u - v) + (x + y) = x.lcm y := by
    rw [hlcm, ← hgx, ← hgy]
    calc
      g * (u * v - u - v) + (g * u + g * v) =
          g * ((u * v - u - v) + (u + v)) := by ring
      _ = g * (u * v) := by rw [hFadd]
  have hscaled_lt : g * (u * v - u - v) < M := by omega
  have hnorm : u * v - u - v < m := by
    apply (Nat.mul_lt_mul_left hg).mp
    rw [hgM]
    exact hscaled_lt
  have hcop : u.Coprime v := by
    dsimp [u, v, g]
    exact Nat.coprime_div_gcd_div_gcd
      (Nat.gcd_pos_of_pos_left y hx)
  obtain ⟨r, s, hrs⟩ :=
    coprime_frobenius_bound hcop (by omega) (by omega) hnorm
  refine ⟨r, s, ?_⟩
  rw [← hgM, ← hgx, ← hgy, hrs]
  ring

lemma mem_representedIndices {a b : ℕ} {J : Finset Index} {i : Index} :
    i ∈ representedIndices a b J ↔ Represented a b J i := by
  classical
  simp [representedIndices]

lemma twoGenerated_mem_semigroup
    {b n : ℕ} {J : Finset Index} {j k : Index}
    (hj : j ∈ J) (hk : k ∈ J)
    (hgen : TwoGenerated (weight b j) (weight b k) n) :
    n ∈ weightSemigroup b J := by
  obtain ⟨r, s, rfl⟩ := hgen
  have hj' := weight_mem_semigroup (b := b) hj
  have hk' := weight_mem_semigroup (b := b) hk
  simpa [nsmul_eq_mul, Nat.mul_comm] using
    (weightSemigroup b J).add_mem
      ((weightSemigroup b J).nsmul_mem hj' r)
      ((weightSemigroup b J).nsmul_mem hk' s)

lemma threeGenerated_mem_semigroup
    {b n : ℕ} {J : Finset Index} {j k l : Index}
    (hj : j ∈ J) (hk : k ∈ J) (hl : l ∈ J)
    (hgen : ThreeGenerated (weight b j) (weight b k) (weight b l) n) :
    n ∈ weightSemigroup b J := by
  obtain ⟨r, s, t, rfl⟩ := hgen
  have hj' := weight_mem_semigroup (b := b) hj
  have hk' := weight_mem_semigroup (b := b) hk
  have hl' := weight_mem_semigroup (b := b) hl
  simpa [nsmul_eq_mul, Nat.mul_comm] using
    (weightSemigroup b J).add_mem
      ((weightSemigroup b J).add_mem
        ((weightSemigroup b J).nsmul_mem hj' r)
        ((weightSemigroup b J).nsmul_mem hk' s))
      ((weightSemigroup b J).nsmul_mem hl' t)

lemma singleton_index_covered
    {a b : ℕ} (hb : 1 ≤ b) (hcyclo : CyclotomicCondition a b)
    (j : Index) :
    ∃ i : Index, weight b j ∣ degree a i := by
  obtain ⟨i, hi, hdiv⟩ :=
    singleton_weight_is_covered hb j.isLt hcyclo
  exact ⟨⟨i, hi⟩, by simpa [weight, degree] using hdiv⟩

/-- Section 3's complete pair argument. For any two distinct denominator
weights, two distinct numerator degrees lie in their generated semigroup. -/
theorem pair_degrees_are_generated
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (hcyclo : CyclotomicCondition a b)
    (j k : Index) (hjk : j ≠ k) :
    ∃ r s : Index, r ≠ s ∧
      TwoGenerated (weight b j) (weight b k) (degree a r) ∧
      TwoGenerated (weight b j) (weight b k) (degree a s) := by
  let x := weight b j
  let y := weight b k
  have hx : 0 < x := by dsimp [x, weight]; omega
  have hy : 0 < y := by dsimp [y, weight]; omega
  have hval : (j : ℕ) ≠ (k : ℕ) := by
    intro h
    exact hjk (Fin.ext h)
  have hxyne : x ≠ y := by
    dsimp [x, y, weight]
    omega
  obtain ⟨ix, hix⟩ := singleton_index_covered hb hcyclo j
  obtain ⟨iy, hiy⟩ := singleton_index_covered hb hcyclo k
  by_cases hindices : ix = iy
  · subst iy
    let N := degree a ix
    let g := x.gcd y
    have hgN : g ∣ N :=
      dvd_trans (Nat.gcd_dvd_left x y) hix
    have hNx : x ∣ N := hix
    have hNy : y ∣ N := hiy
    have hNpos : 0 < N := by dsimp [N, degree]; omega
    have hlcmN : x.lcm y ≤ N :=
      Nat.le_of_dvd hNpos (Nat.lcm_dvd hNx hNy)
    have htwo :
        ∃ r s : Index, r ≠ s ∧
          g ∣ degree a r ∧ g ∣ degree a s := by
      by_cases hg1 : g = 1
      · exact ⟨⟨0, by decide⟩, ⟨1, by decide⟩, by decide,
          by simp [hg1], by simp [hg1]⟩
      · have hg2 : 2 ≤ g := by
          have hg0 : g ≠ 0 := by
            dsimp [g]
            exact Nat.gcd_ne_zero_left hx.ne'
          exact (Nat.two_le_iff g).2 ⟨hg0, hg1⟩
        have hden : 1 < multiplicity b g := by
          rw [multiplicity, Finset.one_lt_card]
          refine ⟨j, ?_, k, ?_, hval⟩
          · exact Finset.mem_filter.mpr
              ⟨Finset.mem_range.mpr j.isLt,
                by simpa [g, x, weight] using Nat.gcd_dvd_left x y⟩
          · exact Finset.mem_filter.mpr
              ⟨Finset.mem_range.mpr k.isLt,
                by simpa [g, y, weight] using Nat.gcd_dvd_right x y⟩
        have hnum : 1 < multiplicity a g :=
          lt_of_lt_of_le hden (hcyclo g hg2)
        rw [multiplicity, Finset.one_lt_card] at hnum
        obtain ⟨r, hr, s, hs, hrs⟩ := hnum
        exact ⟨⟨r, (Finset.mem_filter.mp hr).1 |> Finset.mem_range.mp⟩,
          ⟨s, (Finset.mem_filter.mp hs).1 |> Finset.mem_range.mp⟩,
          by intro h; apply hrs; exact congrArg Fin.val h,
          (Finset.mem_filter.mp hr).2,
          (Finset.mem_filter.mp hs).2⟩
    obtain ⟨r, s, hrs, hgr, hgs⟩ := htwo
    have generate_of_gcd :
        ∀ t : Index, g ∣ degree a t →
          TwoGenerated x y (degree a t) := by
      intro t hgt
      by_cases hx1 : x = 1
      · exact ⟨degree a t, 0, by simp [hx1]⟩
      by_cases hy1 : y = 1
      · exact ⟨0, degree a t, by simp [hy1]⟩
      have hsum : 3 < x + y := by omega
      apply pair_frobenius_from_lcm hx hy
      · exact hgt
      · dsimp [N, degree] at hlcmN ⊢
        omega
      · exact hsum
    exact ⟨r, s, hrs, generate_of_gcd r hgr, generate_of_gcd s hgs⟩
  · refine ⟨ix, iy, hindices, ?_, ?_⟩
    · obtain ⟨c, hc⟩ := hix
      exact ⟨c, 0, by simpa [Nat.mul_comm] using hc⟩
    · obtain ⟨c, hc⟩ := hiy
      exact ⟨0, c, by simpa [Nat.mul_comm] using hc⟩

theorem hall_singleton
    {a b : ℕ} (hb : 1 ≤ b) (hcyclo : CyclotomicCondition a b)
    {J : Finset Index} (hJ : J.card = 1) :
    J.card ≤ (representedIndices a b J).card := by
  obtain ⟨j, rfl⟩ := Finset.card_eq_one.mp hJ
  obtain ⟨i, hdiv⟩ := singleton_index_covered hb hcyclo j
  have hmem : i ∈ representedIndices a b {j} := by
    rw [mem_representedIndices]
    exact multiple_weight_mem_semigroup (by simp) hdiv
  rw [Finset.card_singleton]
  exact Finset.card_pos.mpr ⟨i, hmem⟩

theorem hall_pair
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (hcyclo : CyclotomicCondition a b)
    {J : Finset Index} (hJ : J.card = 2) :
    J.card ≤ (representedIndices a b J).card := by
  obtain ⟨j, k, hjk, rfl⟩ := Finset.card_eq_two.mp hJ
  obtain ⟨r, s, hrs, hgr, hgs⟩ :=
    pair_degrees_are_generated ha hb hcyclo j k hjk
  have hr : r ∈ representedIndices a b {j, k} := by
    rw [mem_representedIndices]
    exact twoGenerated_mem_semigroup (by simp) (by simp) hgr
  have hs : s ∈ representedIndices a b {j, k} := by
    rw [mem_representedIndices]
    exact twoGenerated_mem_semigroup (by simp) (by simp) hgs
  rw [Finset.card_insert_of_notMem (by simp [hjk]),
    Finset.card_singleton]
  exact Finset.one_lt_card.mpr ⟨r, hr, s, hs, hrs⟩

/-- A division-algorithm proof of the Frobenius bound for two consecutive
generators.  The hypothesis is the subtraction-free form
`u^2 - u ≤ n`. -/
theorem consecutive_frobenius
    {u n : ℕ} (hu : 1 ≤ u) (hbound : u * u ≤ n + u) :
    TwoGenerated u (u + 1) n := by
  let q := n / u
  let r := n % u
  have hr : r < u := Nat.mod_lt n (by omega)
  have hdecomp : r + q * u = n := by
    simpa [q, r, Nat.mul_comm] using (Nat.mod_add_div n u)
  have hq : u ≤ q + 1 := by
    by_contra h
    have hqu : q + 2 ≤ u := by omega
    have hmul : (q + 2) * u ≤ u * u :=
      Nat.mul_le_mul_right u hqu
    nlinarith only [hbound, hdecomp, hr, hmul]
  have hrq : r ≤ q := by omega
  refine ⟨q - r, r, ?_⟩
  calc
    n = r + q * u := hdecomp.symm
    _ = (q - r) * u + r * (u + 1) := by
      have hsub : q - r + r = q := Nat.sub_add_cancel hrq
      nlinarith only [hsub]

/-- Every integer at or above `T - 1`, where `T = b(b+3)`, is generated by
`b` and `b+1`. -/
theorem generated_by_b_b_add_one
    {b n : ℕ} (hb : 1 ≤ b) (hn : b * (b + 3) - 1 ≤ n) :
    TwoGenerated b (b + 1) n := by
  apply consecutive_frobenius hb
  have hT : 1 ≤ b * (b + 3) := by
    have : 0 < b * (b + 3) := Nat.mul_pos (by omega) (by omega)
    omega
  have hn' : b * (b + 3) ≤ n + 1 := by omega
  nlinarith only [hn']

/-- Every integer at or above `T - 1` is also generated by `b+1` and
`b+2`. -/
theorem generated_by_b_add_one_b_add_two
    {b n : ℕ} (hb : 1 ≤ b) (hn : b * (b + 3) - 1 ≤ n) :
    TwoGenerated (b + 1) (b + 2) n := by
  apply consecutive_frobenius (u := b + 1) (by omega)
  have hT : 1 ≤ b * (b + 3) := by
    have : 0 < b * (b + 3) := Nat.mul_pos (by omega) (by omega)
    omega
  have hn' : b * (b + 3) ≤ n + 1 := by omega
  nlinarith only [hn']

/-- Membership in the semigroup generated by the exceptional triple
`b, b + 2, b + 3`. -/
def ExceptionalTripleGenerated (b n : ℕ) : Prop :=
  ∃ r s t : ℕ, n = r * b + s * (b + 2) + t * (b + 3)

/-- Formal check of the three exceptional identities, followed by the
consecutive-generator Frobenius bound. -/
theorem exceptional_triple_conductor
    {b n : ℕ} (hb : 5 ≤ b) (hn : b * (b + 3) - 1 ≤ n) :
    ExceptionalTripleGenerated b n := by
  let T := b * (b + 3)
  have hTpos : 1 ≤ T := by
    dsimp [T]
    have : 0 < b * (b + 3) := Nat.mul_pos (by omega) (by omega)
    omega
  have hnT : T ≤ n + 1 := by
    dsimp [T] at hTpos ⊢
    omega
  rcases (by omega : n = T - 1 ∨ n = T ∨ n = T + 1 ∨ T + 2 ≤ n) with
      h | h | h | h
  · refine ⟨0, 1, b - 1, ?_⟩
    rw [h]
    dsimp [T]
    have hsub : b - 1 + 1 = b := Nat.sub_add_cancel (by omega)
    have heq :
        0 * b + 1 * (b + 2) + (b - 1) * (b + 3) + 1 =
          b * (b + 3) := by
      nlinarith only [hsub]
    omega
  · refine ⟨0, 0, b, ?_⟩
    rw [h]
    dsimp [T]
    ring
  · refine ⟨1, b - 1, 1, ?_⟩
    rw [h]
    dsimp [T]
    have hsub : b - 1 + 1 = b := Nat.sub_add_cancel (by omega)
    nlinarith only [hsub]
  · obtain ⟨r, s, hrs⟩ :=
      consecutive_frobenius (u := b + 2) (n := n) (by omega) (by
        dsimp [T] at h
        nlinarith only [h])
    exact ⟨0, r, s, by simpa using hrs⟩

lemma exceptionalTriple_to_threeGenerated
    {b n : ℕ} (h : ExceptionalTripleGenerated b n) :
    ThreeGenerated (weight b ⟨0, by decide⟩)
      (weight b ⟨2, by decide⟩) (weight b ⟨3, by decide⟩) n := by
  obtain ⟨r, s, t, h⟩ := h
  exact ⟨r, s, t, by simpa [weight] using h⟩

/-- Section 5: above the gap threshold, every numerator degree belongs to
every three-weight semigroup. -/
theorem hall_triple_large
    {a b : ℕ} (hb : 5 ≤ b) (ha : b * (b + 3) - 1 ≤ a)
    {J : Finset Index} (hJ : J.card = 3) :
    J.card ≤ (representedIndices a b J).card := by
  have hcomp : Jᶜ.card = 1 := by
    rw [Finset.card_compl, Fintype.card_fin, hJ]
  obtain ⟨m, hm⟩ := Finset.card_eq_one.mp hcomp
  have mem_of_ne (q : Index) (hqm : q ≠ m) : q ∈ J := by
    by_contra hq
    have hqc : q ∈ Jᶜ := Finset.mem_compl.mpr hq
    rw [hm] at hqc
    exact hqm (Finset.mem_singleton.mp hqc)
  have hall : ∀ i : Index, i ∈ representedIndices a b J := by
    intro i
    rw [mem_representedIndices]
    have hdegree : b * (b + 3) - 1 ≤ degree a i := by
      dsimp [degree]
      omega
    fin_cases m
    · apply twoGenerated_mem_semigroup
        (mem_of_ne ⟨1, by decide⟩ (by decide))
        (mem_of_ne ⟨2, by decide⟩ (by decide))
      simpa [weight] using
        (generated_by_b_add_one_b_add_two (b := b) (n := degree a i)
          (by omega) hdegree)
    · exact threeGenerated_mem_semigroup
        (mem_of_ne ⟨0, by decide⟩ (by decide))
        (mem_of_ne ⟨2, by decide⟩ (by decide))
        (mem_of_ne ⟨3, by decide⟩ (by decide))
        (exceptionalTriple_to_threeGenerated
          (exceptional_triple_conductor hb hdegree))
    · apply twoGenerated_mem_semigroup
        (mem_of_ne ⟨0, by decide⟩ (by decide))
        (mem_of_ne ⟨1, by decide⟩ (by decide))
      simpa [weight] using
        (generated_by_b_b_add_one (b := b) (n := degree a i)
          (by omega) hdegree)
    · apply twoGenerated_mem_semigroup
        (mem_of_ne ⟨0, by decide⟩ (by decide))
        (mem_of_ne ⟨1, by decide⟩ (by decide))
      simpa [weight] using
        (generated_by_b_b_add_one (b := b) (n := degree a i)
          (by omega) hdegree)
  have heq : representedIndices a b J = Finset.univ :=
    Finset.eq_univ_of_forall hall
  rw [hJ, heq, Finset.card_fin]
  omega

theorem hall_full_large
    {a b : ℕ} (hb : 5 ≤ b) (ha : b * (b + 3) - 1 ≤ a)
    {J : Finset Index} (hJ : J.card = 4) :
    J.card ≤ (representedIndices a b J).card := by
  have hJuniv : J = Finset.univ := by
    apply Finset.eq_univ_of_card
    simpa [Fintype.card_fin] using hJ
  subst J
  have hall : ∀ i : Index, i ∈ representedIndices a b Finset.univ := by
    intro i
    rw [mem_representedIndices]
    apply twoGenerated_mem_semigroup
      (j := ⟨0, by decide⟩) (k := ⟨1, by decide⟩) (by simp) (by simp)
    simpa [weight] using
      (generated_by_b_b_add_one (b := b) (n := degree a i) (by omega)
        (by dsimp [degree]; omega))
  have heq : representedIndices a b Finset.univ = Finset.univ :=
    Finset.eq_univ_of_forall hall
  rw [Finset.card_univ, Fintype.card_fin, heq,
    Finset.card_univ, Fintype.card_fin]

/-- The elementary interval check behind the last `b = 4` triple: if a
four-term block starting at `a ≥ 4` contains at least two of `4, 8, 9`,
then it contains both `8` and `9`, and its start is `6`, `7`, or `8`. -/
theorem b_four_only_dangerous_starts
    {a : ℕ} (ha : 4 ≤ a)
    (hcard :
      2 ≤ (({4, 8, 9} : Finset ℕ).filter
        (fun n ↦ a ≤ n ∧ n ≤ a + 3)).card) :
    a = 6 ∨ a = 7 ∨ a = 8 := by
  have htwo :
      1 < (({4, 8, 9} : Finset ℕ).filter
        (fun n ↦ a ≤ n ∧ n ≤ a + 3)).card := by omega
  obtain ⟨x, hx, y, hy, hxy⟩ := Finset.one_lt_card.mp htwo
  simp only [Finset.mem_filter, Finset.mem_insert, Finset.mem_singleton] at hx hy
  rcases hx.1 with rfl | rfl | rfl <;>
    rcases hy.1 with rfl | rfl | rfl <;> omega

/-- Start `a = 6` is ruled out by the `d = 5` cyclotomic inequality. -/
theorem not_cyclotomic_six_four : ¬ CyclotomicCondition 6 4 := by
  intro h
  have hc := h 5 (by norm_num)
  have hb : multiplicity 4 5 = 1 := by decide
  have ha : multiplicity 6 5 = 0 := by decide
  omega

/-- Starts `a = 7` and `a = 8` are ruled out by the `d = 6`
cyclotomic inequality. -/
theorem not_cyclotomic_seven_four : ¬ CyclotomicCondition 7 4 := by
  intro h
  have hc := h 6 (by norm_num)
  have hb : multiplicity 4 6 = 1 := by decide
  have ha : multiplicity 7 6 = 0 := by decide
  omega

theorem not_cyclotomic_eight_four : ¬ CyclotomicCondition 8 4 := by
  intro h
  have hc := h 6 (by norm_num)
  have hb : multiplicity 4 6 = 1 := by decide
  have ha : multiplicity 8 6 = 0 := by decide
  omega

/-- The `b = 3` cyclotomic count forces the numerator block to start at a
multiple of three. -/
theorem cyclotomic_three_dvd
    {a : ℕ} (hcyclo : CyclotomicCondition a 3) :
    3 ∣ a := by
  have hden : multiplicity 3 3 = 2 := by decide
  have hnum : 2 ≤ multiplicity a 3 := by
    simpa [hden] using hcyclo 3 (by omega)
  have htwo : 1 < multiplicity a 3 := by omega
  rw [multiplicity, Finset.one_lt_card] at htwo
  obtain ⟨r, hr, s, hs, hrs⟩ := htwo
  have hrlt := Finset.mem_range.mp (Finset.mem_filter.mp hr).1
  have hslt := Finset.mem_range.mp (Finset.mem_filter.mp hs).1
  have hdr := (Finset.mem_filter.mp hr).2
  have hds := (Finset.mem_filter.mp hs).2
  obtain ⟨u, hu⟩ := hdr
  obtain ⟨v, hv⟩ := hds
  have hzero : r = 0 ∨ s = 0 := by omega
  rcases hzero with rfl | rfl
  · exact ⟨u, by simpa using hu⟩
  · exact ⟨v, by simpa using hv⟩

def badIndices (a : ℕ) (G : Finset ℕ) : Finset Index :=
  Finset.univ.filter fun i ↦ degree a i ∈ G

lemma badIndices_singleton_le_one (a g : ℕ) :
    (badIndices a {g}).card ≤ 1 := by
  rw [Finset.card_le_one]
  intro i hi j hj
  simp [badIndices, degree] at hi hj
  exact Fin.ext (by omega)

lemma badIndices_pair_far_le_one
    {a g h : ℕ} (hfar : g + 3 < h ∨ h + 3 < g) :
    (badIndices a {g, h}).card ≤ 1 := by
  rw [Finset.card_le_one]
  intro i hi j hj
  simp only [badIndices, Finset.mem_filter, Finset.mem_univ, true_and,
    Finset.mem_insert, Finset.mem_singleton] at hi hj
  rcases hi with hi | hi <;> rcases hj with hj | hj
  · exact Fin.ext (by dsimp [degree] at hi hj; omega)
  · exfalso
    dsimp [degree] at hi hj
    omega
  · exfalso
    dsimp [degree] at hi hj
    omega
  · exact Fin.ext (by dsimp [degree] at hi hj; omega)

lemma badIndices_47_le_one_of_three_dvd
    {a : ℕ} (hdiv : 3 ∣ a) :
    (badIndices a {4, 7}).card ≤ 1 := by
  rw [Finset.card_le_one]
  intro i hi j hj
  obtain ⟨c, rfl⟩ := hdiv
  simp only [badIndices, Finset.mem_filter, Finset.mem_univ, true_and,
    Finset.mem_insert, Finset.mem_singleton] at hi hj
  rcases hi with hi | hi <;> rcases hj with hj | hj
  · exact Fin.ext (by dsimp [degree] at hi hj; omega)
  · exfalso
    dsimp [degree] at hi hj
    omega
  · exfalso
    dsimp [degree] at hi hj
    omega
  · exact Fin.ext (by dsimp [degree] at hi hj; omega)

lemma badIndices_489_le_one
    {a : ℕ} (ha : 4 ≤ a) (hcyclo : CyclotomicCondition a 4) :
    (badIndices a {4, 8, 9}).card ≤ 1 := by
  rw [Finset.card_le_one]
  intro i hi j hj
  by_contra hij
  have hval : (i : ℕ) ≠ (j : ℕ) := by
    intro h
    exact hij (Fin.ext h)
  simp only [badIndices, Finset.mem_filter, Finset.mem_univ, true_and,
    Finset.mem_insert, Finset.mem_singleton] at hi hj
  rcases hi with hi | hi | hi <;> rcases hj with hj | hj | hj
  all_goals
    dsimp [degree] at hi hj
  all_goals try omega
  all_goals
    have hstart : a = 6 ∨ a = 7 ∨ a = 8 := by omega
    rcases hstart with rfl | rfl | rfl
    · exact not_cyclotomic_six_four hcyclo
    · exact not_cyclotomic_seven_four hcyclo
    · exact not_cyclotomic_eight_four hcyclo

/-- If every degree outside a finite gap set is represented and a
four-term degree block meets that gap set at most once, at least three
degrees are represented. -/
theorem represented_card_ge_three_of_gaps
    {a b : ℕ} {J : Finset Index} (G : Finset ℕ)
    (hbad : (badIndices a G).card ≤ 1)
    (hrep : ∀ i : Index, degree a i ∉ G → Represented a b J i) :
    3 ≤ (representedIndices a b J).card := by
  have hsub : (representedIndices a b J)ᶜ ⊆ badIndices a G := by
    intro i hi
    rw [Finset.mem_compl] at hi
    rw [badIndices, Finset.mem_filter]
    refine ⟨Finset.mem_univ _, ?_⟩
    by_contra hgap
    exact hi (mem_representedIndices.mpr (hrep i hgap))
  have hcard := Finset.card_le_card hsub
  rw [Finset.card_compl, Fintype.card_fin] at hcard
  omega

/-- Section 6's complete three-weight check. -/
theorem hall_triple_small
    {a b : ℕ} (hb : 1 ≤ b) (hb4 : b ≤ 4) (ha : b ≤ a)
    (hcyclo : CyclotomicCondition a b)
    {J : Finset Index} (hJ : J.card = 3) :
    J.card ≤ (representedIndices a b J).card := by
  have hcomp : Jᶜ.card = 1 := by
    rw [Finset.card_compl, Fintype.card_fin, hJ]
  obtain ⟨m, hm⟩ := Finset.card_eq_one.mp hcomp
  have mem_of_ne (q : Index) (hqm : q ≠ m) : q ∈ J := by
    by_contra hq
    have hqc : q ∈ Jᶜ := Finset.mem_compl.mpr hq
    rw [hm] at hqc
    exact hqm (Finset.mem_singleton.mp hqc)
  have finish (G : Finset ℕ)
      (hbad : (badIndices a G).card ≤ 1)
      (hgen : ∀ i : Index, degree a i ∉ G →
        degree a i ∈ weightSemigroup b J) :
      J.card ≤ (representedIndices a b J).card := by
    rw [hJ]
    exact represented_card_ge_three_of_gaps G hbad hgen
  interval_cases b <;> fin_cases m
  · -- b=1, J={1,2,3}, weights 2,3,4
    apply finish {1} (badIndices_singleton_le_one a 1)
    intro i hi
    apply threeGenerated_mem_semigroup
      (mem_of_ne ⟨1, by decide⟩ (by decide))
      (mem_of_ne ⟨2, by decide⟩ (by decide))
      (mem_of_ne ⟨3, by decide⟩ (by decide))
    simpa [weight] using generated_234 (n := degree a i) (by
      simp only [Finset.mem_singleton] at hi
      dsimp [degree] at hi ⊢
      omega)
  · -- b=1, the remaining triples contain weight 1
    apply finish ∅ (by simp [badIndices])
    intro i hi
    exact multiple_weight_mem_semigroup
      (mem_of_ne ⟨0, by decide⟩ (by decide)) (by simp [weight])
  · apply finish ∅ (by simp [badIndices])
    intro i hi
    exact multiple_weight_mem_semigroup
      (mem_of_ne ⟨0, by decide⟩ (by decide)) (by simp [weight])
  · apply finish ∅ (by simp [badIndices])
    intro i hi
    exact multiple_weight_mem_semigroup
      (mem_of_ne ⟨0, by decide⟩ (by decide)) (by simp [weight])
  · -- b=2, J={1,2,3}, weights 3,4,5; only gap 2
    apply finish {2} (badIndices_singleton_le_one a 2)
    intro i hi
    apply threeGenerated_mem_semigroup
      (mem_of_ne ⟨1, by decide⟩ (by decide))
      (mem_of_ne ⟨2, by decide⟩ (by decide))
      (mem_of_ne ⟨3, by decide⟩ (by decide))
    simpa [weight] using generated_345 (n := degree a i) (by
      simp only [Finset.mem_singleton] at hi
      dsimp [degree] at hi ⊢
      omega)
  · -- weights 2,4,5; only gap 3
    apply finish {3} (badIndices_singleton_le_one a 3)
    intro i hi
    apply threeGenerated_mem_semigroup
      (mem_of_ne ⟨0, by decide⟩ (by decide))
      (mem_of_ne ⟨2, by decide⟩ (by decide))
      (mem_of_ne ⟨3, by decide⟩ (by decide))
    simpa [weight] using generated_245 (n := degree a i) (by
      dsimp [degree]; omega) (by simpa using hi)
  · -- weights 2,3,5
    apply finish ∅ (by simp [badIndices])
    intro i hi
    apply threeGenerated_mem_semigroup
      (mem_of_ne ⟨0, by decide⟩ (by decide))
      (mem_of_ne ⟨1, by decide⟩ (by decide))
      (mem_of_ne ⟨3, by decide⟩ (by decide))
    simpa [weight] using generated_235 (n := degree a i) (by
      dsimp [degree]; omega)
  · -- weights 2,3,4
    apply finish ∅ (by simp [badIndices])
    intro i hi
    apply threeGenerated_mem_semigroup
      (mem_of_ne ⟨0, by decide⟩ (by decide))
      (mem_of_ne ⟨1, by decide⟩ (by decide))
      (mem_of_ne ⟨2, by decide⟩ (by decide))
    simpa [weight] using generated_234 (n := degree a i) (by
      dsimp [degree]; omega)
  · -- b=3, weights 4,5,6; gaps 3,7
    apply finish {3, 7} (badIndices_pair_far_le_one (by omega))
    intro i hi
    apply threeGenerated_mem_semigroup
      (mem_of_ne ⟨1, by decide⟩ (by decide))
      (mem_of_ne ⟨2, by decide⟩ (by decide))
      (mem_of_ne ⟨3, by decide⟩ (by decide))
    apply generated_456 (n := degree a i) (by dsimp [degree]; omega)
    · simpa using fun h : degree a i = 3 ↦ hi (by simp [h])
    · simpa using fun h : degree a i = 7 ↦ hi (by simp [h])
  · -- weights 3,5,6; gaps 4,7
    apply finish {4, 7} (badIndices_47_le_one_of_three_dvd
      (cyclotomic_three_dvd hcyclo))
    intro i hi
    apply threeGenerated_mem_semigroup
      (mem_of_ne ⟨0, by decide⟩ (by decide))
      (mem_of_ne ⟨2, by decide⟩ (by decide))
      (mem_of_ne ⟨3, by decide⟩ (by decide))
    apply generated_356 (n := degree a i) (by dsimp [degree]; omega)
    · simpa using fun h : degree a i = 4 ↦ hi (by simp [h])
    · simpa using fun h : degree a i = 7 ↦ hi (by simp [h])
  · -- weights 3,4,6; gap 5
    apply finish {5} (badIndices_singleton_le_one a 5)
    intro i hi
    apply threeGenerated_mem_semigroup
      (mem_of_ne ⟨0, by decide⟩ (by decide))
      (mem_of_ne ⟨1, by decide⟩ (by decide))
      (mem_of_ne ⟨3, by decide⟩ (by decide))
    apply generated_346 (n := degree a i) (by dsimp [degree]; omega)
    simpa using fun h : degree a i = 5 ↦ hi (by simp [h])
  · -- weights 3,4,5
    apply finish ∅ (by simp [badIndices])
    intro i hi
    apply threeGenerated_mem_semigroup
      (mem_of_ne ⟨0, by decide⟩ (by decide))
      (mem_of_ne ⟨1, by decide⟩ (by decide))
      (mem_of_ne ⟨2, by decide⟩ (by decide))
    simpa [weight] using generated_345 (n := degree a i) (by
      dsimp [degree]; omega)
  · -- b=4, weights 5,6,7; gaps 4,8,9
    apply finish {4, 8, 9} (badIndices_489_le_one ha hcyclo)
    intro i hi
    apply threeGenerated_mem_semigroup
      (mem_of_ne ⟨1, by decide⟩ (by decide))
      (mem_of_ne ⟨2, by decide⟩ (by decide))
      (mem_of_ne ⟨3, by decide⟩ (by decide))
    apply generated_567 (n := degree a i) (by dsimp [degree]; omega)
    · simpa using fun h : degree a i = 4 ↦ hi (by simp [h])
    · simpa using fun h : degree a i = 8 ↦ hi (by simp [h])
    · simpa using fun h : degree a i = 9 ↦ hi (by simp [h])
  · -- weights 4,6,7; gaps 5,9
    apply finish {5, 9} (badIndices_pair_far_le_one (by omega))
    intro i hi
    apply threeGenerated_mem_semigroup
      (mem_of_ne ⟨0, by decide⟩ (by decide))
      (mem_of_ne ⟨2, by decide⟩ (by decide))
      (mem_of_ne ⟨3, by decide⟩ (by decide))
    apply generated_467 (n := degree a i) (by dsimp [degree]; omega)
    · simpa using fun h : degree a i = 5 ↦ hi (by simp [h])
    · simpa using fun h : degree a i = 9 ↦ hi (by simp [h])
  · -- weights 4,5,7; gap 6
    apply finish {6} (badIndices_singleton_le_one a 6)
    intro i hi
    apply threeGenerated_mem_semigroup
      (mem_of_ne ⟨0, by decide⟩ (by decide))
      (mem_of_ne ⟨1, by decide⟩ (by decide))
      (mem_of_ne ⟨3, by decide⟩ (by decide))
    apply generated_457 (n := degree a i) (by dsimp [degree]; omega)
    simpa using fun h : degree a i = 6 ↦ hi (by simp [h])
  · -- weights 4,5,6; gap 7
    apply finish {7} (badIndices_singleton_le_one a 7)
    intro i hi
    apply threeGenerated_mem_semigroup
      (mem_of_ne ⟨0, by decide⟩ (by decide))
      (mem_of_ne ⟨1, by decide⟩ (by decide))
      (mem_of_ne ⟨2, by decide⟩ (by decide))
    apply generated_456 (n := degree a i) (by dsimp [degree]; omega)
    · intro h
      dsimp [degree] at h
      omega
    · simpa using fun h : degree a i = 7 ↦ hi (by simp [h])

/-- Section 6's four-weight condition. -/
theorem hall_full_small
    {a b : ℕ} (hb : 1 ≤ b) (hb4 : b ≤ 4) (ha : b ≤ a)
    {J : Finset Index} (hJ : J.card = 4) :
    J.card ≤ (representedIndices a b J).card := by
  have hJuniv : J = Finset.univ := by
    apply Finset.eq_univ_of_card
    simpa [Fintype.card_fin] using hJ
  subst J
  have hall : ∀ i : Index, i ∈ representedIndices a b Finset.univ := by
    intro i
    rw [mem_representedIndices]
    interval_cases b
    · exact multiple_weight_mem_semigroup
        (j := ⟨0, by decide⟩) (by simp) (by simp [weight])
    · apply threeGenerated_mem_semigroup
        (j := ⟨0, by decide⟩) (k := ⟨1, by decide⟩)
        (l := ⟨2, by decide⟩) (by simp) (by simp) (by simp)
      simpa [weight] using generated_234 (n := degree a i) (by
        dsimp [degree]
        omega)
    · apply threeGenerated_mem_semigroup
        (j := ⟨0, by decide⟩) (k := ⟨1, by decide⟩)
        (l := ⟨2, by decide⟩) (by simp) (by simp) (by simp)
      simpa [weight] using generated_345 (n := degree a i) (by
        dsimp [degree]
        omega)
    · by_cases h7 : degree a i = 7
      · exact multiple_weight_mem_semigroup
          (j := ⟨3, by decide⟩) (by simp) (by simp [weight, h7])
      · apply threeGenerated_mem_semigroup
          (j := ⟨0, by decide⟩) (k := ⟨1, by decide⟩)
          (l := ⟨2, by decide⟩) (by simp) (by simp) (by simp)
        simpa [weight] using generated_456 (n := degree a i)
          (by dsimp [degree]; omega) (by dsimp [degree]; omega) h7
  have heq : representedIndices a b Finset.univ = Finset.univ :=
    Finset.eq_univ_of_forall hall
  rw [Finset.card_univ, Fintype.card_fin, heq,
    Finset.card_univ, Fintype.card_fin]

/-- The complete arithmetic conclusion of Sections 1 and 3--6: the
cyclotomic inequalities imply every semigroup cardinality condition (3). -/
theorem hallCondition_of_cyclotomic
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (hcyclo : CyclotomicCondition a b) :
    HallCondition a b := by
  have hab : b ≤ a := cyclotomic_implies_a_ge_b ha hb hcyclo
  intro J hJnonempty
  by_cases heq : a = b
  · subst a
    have hsub : J ⊆ representedIndices b b J := by
      intro i hi
      rw [mem_representedIndices]
      apply multiple_weight_mem_semigroup hi
      simp [weight, degree]
    exact Finset.card_le_card hsub
  have hcardpos : 0 < J.card := Finset.card_pos.mpr hJnonempty
  have hcardle : J.card ≤ 4 := by
    calc
      J.card ≤ (Finset.univ : Finset Index).card := Finset.card_le_univ J
      _ = 4 := Finset.card_fin 4
  rcases (by omega : J.card = 1 ∨ J.card = 2 ∨ J.card = 3 ∨ J.card = 4) with
      h1 | h2 | h3 | h4
  · exact hall_singleton hb hcyclo h1
  · exact hall_pair ha hb hcyclo h2
  · by_cases hb4 : b ≤ 4
    · exact hall_triple_small hb hb4 hab hcyclo h3
    · have hb5 : 5 ≤ b := by omega
      have hlarge : b * (b + 3) - 1 ≤ a := by
        rcases gap_lemma ha hb5 hcyclo with h | h
        · exact False.elim (heq h)
        · exact h
      exact hall_triple_large hb5 hlarge h3
  · by_cases hb4 : b ≤ 4
    · exact hall_full_small hb hb4 hab h4
    · have hb5 : 5 ≤ b := by omega
      have hlarge : b * (b + 3) - 1 ≤ a := by
        rcases gap_lemma ha hb5 hcyclo with h | h
        · exact False.elim (heq h)
        · exact h
      exact hall_full_large hb5 hlarge h4

/-- End-to-end machine-checked reduction from polynomiality of the quotient
to every semigroup condition (3). -/
theorem hallCondition_of_polynomialQuotient
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (hpoly : IsPolynomialQuotient a b) :
    HallCondition a b :=
  hallCondition_of_cyclotomic ha hb
    (cyclotomicCondition_of_polynomialQuotient ha hb hpoly)

/-- Direct paper-level version: divisibility of the product of four literal
`q`-integers implies every Hall condition. -/
theorem hallCondition_of_qIntegerPolynomialQuotient
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (hpoly : IsQIntegerPolynomialQuotient a b) :
    HallCondition a b :=
  hallCondition_of_polynomialQuotient ha hb
    ((isQIntegerPolynomialQuotient_iff a b).mp hpoly)

/-- A direct degree check, independently confirming that polynomiality of the
literal quotient forces `b ≤ a`. -/
theorem qIntegerPolynomialQuotient_implies_b_le_a
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (hpoly : IsQIntegerPolynomialQuotient a b) :
    b ≤ a := by
  have hdeg := Polynomial.natDegree_le_of_dvd hpoly
    (qIntegerProduct_ne_zero a ha)
  rw [qIntegerProduct_natDegree a ha,
    qIntegerProduct_natDegree b hb] at hdeg
  omega

/-- The one remaining algebraic interface has Aristotle's coefficientwise
`ci_positivity` conclusion, restricted to the paper's positive domain.
The guards `1 ≤ a` and `1 ≤ b` are essential: without them, the unguarded
statement fails at `a = b = 0`, where both products vanish. Under the Hall
condition, any existing quotient polynomial has nonnegative integer
coefficients. -/
def WeightedCompleteIntersectionBridge : Prop :=
  ∀ a b : ℕ, 1 ≤ a → 1 ≤ b → HallCondition a b →
    ∀ P : Polynomial ℤ,
      qIntegerProduct b * P = qIntegerProduct a →
      ∀ n, 0 ≤ P.coeff n

/-- **External theorem: weighted complete-intersection positivity.**

This is the direct combination of Propositions 3.3 and 3.6 in:

* M. Gatzweiler, F. Levicán-Santibáñez, and A. Yoshida,
  *Cyclotomic generating functions, empty weighted complete intersections
  and positivity*, arXiv:2603.22226v1 (2026),
  https://doi.org/10.48550/arXiv.2603.22226.

Proposition 3.3 identifies the semigroup-cardinality condition with existence
of a homogeneous regular sequence of the prescribed positive degrees and
weights. Proposition 3.6 proves that its Hilbert-series quotient has
nonnegative coefficients. Instantiating their multisets with
`[a, a+1, a+2, a+3]` and `[b, b+1, b+2, b+3]` gives exactly this declaration.

This named axiom is the only project-specific external assumption. Every
cyclotomic, numerical-semigroup, gap, exceptional-case, and theorem-assembly
step is proved in Lean. -/
axiom weightedCompleteIntersectionBridge_external :
  WeightedCompleteIntersectionBridge

/-- Aristotle's coefficientwise formulation, now derived without placeholders
from the explicit weighted-complete-intersection hypothesis. -/
theorem qInteger_quotient_coeff_nonnegative_of_weightedCompleteIntersection
    (hWCI : WeightedCompleteIntersectionBridge)
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (P : Polynomial ℤ)
    (hP : qIntegerProduct b * P = qIntegerProduct a) :
    ∀ n, 0 ≤ P.coeff n :=
  hWCI a b ha hb
    (hallCondition_of_qIntegerPolynomialQuotient ha hb ⟨P, hP.symm⟩)
    P hP

/-- Coefficient positivity stated directly for the paper's literal
`q`-integer quotient. The conversion from nonnegative integer coefficients
to a polynomial over `ℕ` is proved in
`coefficientwiseToNat_map_of_nonnegative`. -/
theorem qInteger_quotient_positivity_of_weightedCompleteIntersection
    (hWCI : WeightedCompleteIntersectionBridge)
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (hpoly : IsQIntegerPolynomialQuotient a b) :
    HasNonnegativeQIntegerQuotient a b := by
  obtain ⟨P, hP⟩ := hpoly
  have hcoeff : ∀ n, 0 ≤ P.coeff n :=
    qInteger_quotient_coeff_nonnegative_of_weightedCompleteIntersection
      hWCI ha hb P hP.symm
  refine ⟨coefficientwiseToNat P, ?_⟩
  rw [coefficientwiseToNat_map_of_nonnegative P hcoeff]
  exact hP

/-- The exact coefficient-positivity theorem follows from the Section 2
bridge and the fully checked arithmetic reduction. This theorem has no
hidden axiom: the bridge is an explicit hypothesis. -/
theorem quotient_positivity_of_weightedCompleteIntersection
    (hWCI : WeightedCompleteIntersectionBridge)
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (hpoly : IsPolynomialQuotient a b) :
    HasNonnegativeQuotient a b := by
  rw [← hasNonnegativeQIntegerQuotient_iff]
  exact qInteger_quotient_positivity_of_weightedCompleteIntersection
    hWCI ha hb ((isQIntegerPolynomialQuotient_iff a b).mpr hpoly)

/-- Index-gap-four parameters `a = n-k+1`, `b = k-3`. -/
theorem q_binomial_quotient_positivity_gap_four_of_weightedCompleteIntersection
    (hWCI : WeightedCompleteIntersectionBridge)
    {n k : ℕ} (hk : 4 ≤ k) (hkn : k ≤ n)
    (hpoly : IsPolynomialQuotient (n - k + 1) (k - 3)) :
    HasNonnegativeQuotient (n - k + 1) (k - 3) := by
  apply quotient_positivity_of_weightedCompleteIntersection hWCI
  · have hrewrite : n - k + 1 = n + 1 - k := by omega
    rw [hrewrite]
    omega
  · omega
  · exact hpoly

/-- Index-gap-four parameters, with polynomiality and positivity stated for
the literal products of `q`-integers in the conjecture. -/
theorem q_binomial_qInteger_quotient_positivity_gap_four_of_weightedCompleteIntersection
    (hWCI : WeightedCompleteIntersectionBridge)
    {n k : ℕ} (hk : 4 ≤ k) (hkn : k ≤ n)
    (hpoly :
      IsQIntegerPolynomialQuotient (n - k + 1) (k - 3)) :
    HasNonnegativeQIntegerQuotient (n - k + 1) (k - 3) := by
  apply qInteger_quotient_positivity_of_weightedCompleteIntersection hWCI
  · have hrewrite : n - k + 1 = n + 1 - k := by omega
    rw [hrewrite]
    omega
  · omega
  · exact hpoly

/-! ## Publication theorem -/

/-- Polynomiality of the normalized four-factor quotient implies
coefficientwise nonnegativity. The only external dependency is
`weightedCompleteIntersectionBridge_external`. -/
theorem quotient_positivity
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (hpoly : IsPolynomialQuotient a b) :
    HasNonnegativeQuotient a b :=
  quotient_positivity_of_weightedCompleteIntersection
    weightedCompleteIntersectionBridge_external ha hb hpoly

/-- The same result for the literal product of four `q`-integers. -/
theorem qInteger_quotient_positivity
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (hpoly : IsQIntegerPolynomialQuotient a b) :
    HasNonnegativeQIntegerQuotient a b :=
  qInteger_quotient_positivity_of_weightedCompleteIntersection
    weightedCompleteIntersectionBridge_external ha hb hpoly

/-- Coefficientwise positivity, discharged by the single cited external
bridge after the machine-checked Hall reduction. -/
theorem qInteger_quotient_coeff_nonnegative
    {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b)
    (P : Polynomial ℤ)
    (hP : qIntegerProduct b * P = qIntegerProduct a) :
    ∀ n, 0 ≤ P.coeff n :=
  qInteger_quotient_coeff_nonnegative_of_weightedCompleteIntersection
    weightedCompleteIntersectionBridge_external ha hb P hP

/-- Index-gap-four q-binomial parameters `a = n-k+1`, `b = k-3`. -/
theorem q_binomial_quotient_positivity_gap_four
    {n k : ℕ} (hk : 4 ≤ k) (hkn : k ≤ n)
    (hpoly : IsPolynomialQuotient (n - k + 1) (k - 3)) :
    HasNonnegativeQuotient (n - k + 1) (k - 3) :=
  q_binomial_quotient_positivity_gap_four_of_weightedCompleteIntersection
    weightedCompleteIntersectionBridge_external hk hkn hpoly

/-- Index-gap-four parameters for the literal `q`-integer quotient. -/
theorem q_binomial_qInteger_quotient_positivity_gap_four
    {n k : ℕ} (hk : 4 ≤ k) (hkn : k ≤ n)
    (hpoly :
      IsQIntegerPolynomialQuotient (n - k + 1) (k - 3)) :
    HasNonnegativeQIntegerQuotient (n - k + 1) (k - 3) :=
  q_binomial_qInteger_quotient_positivity_gap_four_of_weightedCompleteIntersection
    weightedCompleteIntersectionBridge_external hk hkn hpoly

end QBinomialQuotientPositivityGapFour
